### ISSUE TITLE
What is this tailing for ?

### ISSUE THREAD

**Issue by l15k4** [alaz/tailf#1]
Hi Alex,

I can't figure out what is this good for. It allows for surviving log rotation and still keep the handle to the log file that is backed up. But at that point it makes no sense to keep reading such file, right ?

Wouldn't it make more sense if it was able to continue with reading the new file that was created after the old was rotated? So that it could feel like it is reading one file but actually it would be xth file that it is reading after surviving rotation.

Thank you, Jakub

**Comment by l15k4** [comment]
After debugging the test spec I found out that it is actually behaves the way one would expect, which makes it very useful. I got confused because It is quite unexpected that after following sequence of events : 

file.rename(...)
out = new FileWriter(file)
out.write(s)

it is still writing to the original destination instead of the new one. I hope it will behave the same way if I try to move the file on unix filesystem.

**Comment by alaz** [comment]
Hi Jakub,

As far as I remember the code is written to always read from the file with given name. **file**, not **file handle**. So the code tries to [open the same file name](https://github.com/alaz/tailf/blob/master/src/main/scala/com/osinka/tailf/Tail.scala#L54) after [the previous file seems rotated](https://github.com/alaz/tailf/blob/master/src/main/scala/com/osinka/tailf/Tail.scala#L109).

I'm looking forward to hearing what your investigation will reveal :)

**Comment by l15k4** [comment]
Well it works as expected, except for when you try something like this: 

Source.fromInputStream(Tail.follow(existingFile)).getLines()

and write to that file, it sleeps. I'll have to tweak it some way or another or I will use it directly.

**Comment by l15k4** [comment]
I miss used that, it all works as expected, even when using Scala's BufferedSource. Thank you so much Alex !

**Comment by alaz** [comment]
Good to know everything is ok. Thanks for letting know!
